# Generated by Django 4.0 on 2021-12-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='__', max_length=20, unique=True)),
                ('desc', models.CharField(default='__', max_length=500)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
