# Generated by Django 3.1.6 on 2022-01-29 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_rename_complaint_issuemessage_issue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
