# Generated by Django 4.0 on 2022-01-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_rename_user_id_complaint_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_hash',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
