# Generated by Django 4.0 on 2022-01-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_alter_user_profile_picture_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture_id',
            new_name='profile_picture_file',
        ),
    ]
